server.port = 7077
server.servlet.context-path=/openTradeIMLC
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCL
spring.datasource.username=TEST
spring.datasource.password=TEST@123
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


#spring.datasource.url=jdbc:oracle:thin:@//dev-sbi:1521/SBICE
#spring.datasource.username=CETRX
#spring.datasource.password=CETRX
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=*
